apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: counter-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counter-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Target CPU utilization at 50%
