apiVersion: v1
kind: Service
metadata:
  name: counter-app
spec:
  selector:
    app: counter-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort  # You can change this to LoadBalancer if using a cloud provider
