echo "global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'counter_app'
    static_configs:
      - targets: ['localhost:3000']" > /c/Users/imran/counter-app/prometheus.yml
